// Flappy Bird — single-file build
// Generated by combining models.dart, persistence_service.dart,
// sound_manager.dart, painter.dart, game_screen.dart, and main.dart
// into one file, per request. See PUBSPEC_CHANGES.md for required
// dependencies and asset files.

import 'dart:math';
import 'dart:convert';
import 'dart:ui' as ui;
import 'dart:async';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter/scheduler.dart';
import 'package:video_player/video_player.dart';

// ----------------------- DIFFICULTY -----------------------

enum Difficulty { easy, normal, hard }

class DifficultySettings {
  final double gravity;
  final double flapVelocity;
  final double pipeSpeed;
  final double gapHeight;

  const DifficultySettings({
    required this.gravity,
    required this.flapVelocity,
    required this.pipeSpeed,
    required this.gapHeight,
  });

  static const easy = DifficultySettings(
    gravity: 1200,
    flapVelocity: -380,
    pipeSpeed: 150,
    gapHeight: 240,
  );

  static const normal = DifficultySettings(
    gravity: 1400,
    flapVelocity: -420,
    pipeSpeed: 180,
    gapHeight: 200,
  );

  static const hard = DifficultySettings(
    gravity: 1600,
    flapVelocity: -460,
    pipeSpeed: 220,
    gapHeight: 165,
  );

  static DifficultySettings forMode(Difficulty d) {
    switch (d) {
      case Difficulty.easy:
        return easy;
      case Difficulty.normal:
        return normal;
      case Difficulty.hard:
        return hard;
    }
  }

  static String label(Difficulty d) {
    switch (d) {
      case Difficulty.easy:
        return 'Easy';
      case Difficulty.normal:
        return 'Normal';
      case Difficulty.hard:
        return 'Hard';
    }
  }
}

// ----------------------- POWER-UPS -----------------------

enum PowerUpType { shield, slowMo, magnet }

// ----------------------- PIPES -----------------------

/// A vertical gap the bird can safely pass through.
class GapZone {
  final double top;
  final double bottom;
  const GapZone(this.top, this.bottom);
}

class Pipe {
  double x; // left edge
  double gapCenter;
  double gapHeight;
  final double baseGapCenter;

  // Moving-pipe support: gapCenter drifts sinusoidally around baseGapCenter.
  final bool moving;
  final double driftRange;
  final double driftSpeed;
  double driftPhase;

  // Double-gap pipe support: a second, independent opening.
  final bool isDouble;
  double? secondGapCenter;
  double? secondGapHeight;

  bool scored = false;

  final bool hasPowerUp;
  final PowerUpType? powerUpType;
  bool powerUpCollected = false;

  // Which custom picture (if any) this specific pipe was randomly assigned
  // at spawn time — lets pillars vary in appearance instead of all using
  // the same texture. Null falls back to the solid pipe-theme color.
  final ui.Image? pipeImage;

  Pipe({
    required this.x,
    required this.gapCenter,
    required this.gapHeight,
    this.moving = false,
    this.driftRange = 0,
    this.driftSpeed = 0,
    this.isDouble = false,
    this.secondGapCenter,
    this.secondGapHeight,
    this.hasPowerUp = false,
    this.powerUpType,
    this.pipeImage,
  })  : baseGapCenter = gapCenter,
        driftPhase = 0;

  /// The safe (passable) vertical zones for this pipe, sorted top-to-bottom.
  List<GapZone> gapZones() {
    final zones = <GapZone>[
      GapZone(gapCenter - gapHeight / 2, gapCenter + gapHeight / 2),
    ];
    if (isDouble && secondGapCenter != null && secondGapHeight != null) {
      zones.add(GapZone(
        secondGapCenter! - secondGapHeight! / 2,
        secondGapCenter! + secondGapHeight! / 2,
      ));
    }
    zones.sort((a, b) => a.top.compareTo(b.top));
    return zones;
  }
}

// ----------------------- COINS -----------------------

class Coin {
  double x;
  double y;
  bool collected = false;
  Coin({required this.x, required this.y});
}

// ----------------------- PARTICLES -----------------------

class Particle {
  double x, y, vx, vy;
  double life;
  final double maxLife;
  final int colorValue;
  Particle({
    required this.x,
    required this.y,
    required this.vx,
    required this.vy,
    required this.life,
    required this.colorValue,
  }) : maxLife = life;
}

// ----------------------- COSMETICS -----------------------

class BirdSkin {
  final String id;
  final String name;
  final int unlockCoinCost; // 0 = unlocked from the start
  final int? colorValue; // ARGB tint applied over the bird sprite; null = none
  const BirdSkin({
    required this.id,
    required this.name,
    required this.unlockCoinCost,
    this.colorValue,
  });
}

const List<BirdSkin> kBirdSkins = [
  BirdSkin(id: 'classic', name: 'Classic', unlockCoinCost: 0),
  BirdSkin(id: 'red', name: 'Cardinal', unlockCoinCost: 20, colorValue: 0xFFE53935),
  BirdSkin(id: 'blue', name: 'Bluebird', unlockCoinCost: 20, colorValue: 0xFF1E88E5),
  BirdSkin(id: 'gold', name: 'Golden', unlockCoinCost: 50, colorValue: 0xFFFFC107),
  BirdSkin(id: 'violet', name: 'Violet', unlockCoinCost: 50, colorValue: 0xFF8E24AA),
];

class PipeTheme {
  final String id;
  final String name;
  final int unlockCoinCost;
  final int bodyColor;
  final int edgeColor;
  const PipeTheme({
    required this.id,
    required this.name,
    required this.unlockCoinCost,
    required this.bodyColor,
    required this.edgeColor,
  });
}

const List<PipeTheme> kPipeThemes = [
  PipeTheme(id: 'green', name: 'Classic Green', unlockCoinCost: 0, bodyColor: 0xFF74BF2E, edgeColor: 0xFF528A20),
  PipeTheme(id: 'stone', name: 'Stone Grey', unlockCoinCost: 30, bodyColor: 0xFF9E9E9E, edgeColor: 0xFF616161),
  PipeTheme(id: 'lava', name: 'Lava Red', unlockCoinCost: 60, bodyColor: 0xFFE64A19, edgeColor: 0xFFBF360C),
  PipeTheme(id: 'ice', name: 'Ice Blue', unlockCoinCost: 60, bodyColor: 0xFF4FC3F7, edgeColor: 0xFF0288D1),
];

// ----------------------- ACHIEVEMENTS -----------------------

class GameStats {
  final int bestScore;
  final int gamesPlayed;
  final int totalCoins;
  const GameStats({
    required this.bestScore,
    required this.gamesPlayed,
    required this.totalCoins,
  });
}

class Achievement {
  final String id;
  final String title;
  final String description;
  final bool Function(GameStats stats) isUnlocked;
  const Achievement({
    required this.id,
    required this.title,
    required this.description,
    required this.isUnlocked,
  });
}

List<Achievement> buildAchievements() => [
      Achievement(
        id: 'score_10',
        title: 'Getting Started',
        description: 'Reach a score of 10',
        isUnlocked: (s) => s.bestScore >= 10,
      ),
      Achievement(
        id: 'score_25',
        title: 'Reached 25',
        description: 'Reach a score of 25',
        isUnlocked: (s) => s.bestScore >= 25,
      ),
      Achievement(
        id: 'score_50',
        title: 'Reached 50',
        description: 'Reach a score of 50',
        isUnlocked: (s) => s.bestScore >= 50,
      ),
      Achievement(
        id: 'games_5',
        title: '5 Games Played',
        description: 'Play 5 games',
        isUnlocked: (s) => s.gamesPlayed >= 5,
      ),
      Achievement(
        id: 'games_25',
        title: 'Regular',
        description: 'Play 25 games',
        isUnlocked: (s) => s.gamesPlayed >= 25,
      ),
      Achievement(
        id: 'coins_50',
        title: 'Coin Collector',
        description: 'Collect 50 coins in total',
        isUnlocked: (s) => s.totalCoins >= 50,
      ),
    ];

// ----------------------- LEADERBOARD -----------------------

class LeaderboardEntry {
  final String name;
  final int score;
  const LeaderboardEntry(this.name, this.score);

  Map<String, dynamic> toJson() => {'name': name, 'score': score};
  factory LeaderboardEntry.fromJson(Map<String, dynamic> json) =>
      LeaderboardEntry(json['name'] as String? ?? 'Player', json['score'] as int? ?? 0);
}

// ----------------------- COLLISION HELPER -----------------------

/// Circle-vs-rectangle overlap test (fairer near pipe corners than a plain
/// rect-vs-rect check). Finds the closest point on [rect] to [center] and
/// compares the distance against [radius].
bool circleIntersectsRect(double cx, double cy, double radius, double left,
    double top, double right, double bottom) {
  final closestX = cx.clamp(left, right);
  final closestY = cy.clamp(top, bottom);
  final dx = cx - closestX;
  final dy = cy - closestY;
  return (dx * dx + dy * dy) < (radius * radius);
}

double distanceBetween(double x1, double y1, double x2, double y2) {
  final dx = x1 - x2;
  final dy = y1 - y2;
  return sqrt(dx * dx + dy * dy);
}

// ============================================================

/// Wraps shared_preferences so all of the game's persistent state (high
/// score, leaderboard, currency, unlocked cosmetics/achievements, and
/// settings) survives app restarts. Call [init] once before reading
/// anything from it.
class PersistenceService {
  static const _kHighScore = 'flappy_high_score';
  static const _kLeaderboard = 'flappy_leaderboard_v1';
  static const _kTotalCoins = 'flappy_total_coins';
  static const _kUnlockedSkins = 'flappy_unlocked_skins';
  static const _kSelectedSkin = 'flappy_selected_skin';
  static const _kUnlockedPipeThemes = 'flappy_unlocked_pipe_themes';
  static const _kSelectedPipeTheme = 'flappy_selected_pipe_theme';
  static const _kAchievements = 'flappy_achievements';
  static const _kDifficulty = 'flappy_difficulty';
  static const _kMuted = 'flappy_muted';
  static const _kVolume = 'flappy_volume';
  static const _kGamesPlayed = 'flappy_games_played';
  static const _kPlayerName = 'flappy_player_name';

  SharedPreferences? _prefs;

  Future<void> init() async {
    _prefs = await SharedPreferences.getInstance();
  }

  SharedPreferences get _p {
    final prefs = _prefs;
    if (prefs == null) {
      throw StateError('PersistenceService.init() must complete before use');
    }
    return prefs;
  }

  int get highScore => _p.getInt(_kHighScore) ?? 0;
  Future<void> setHighScore(int v) => _p.setInt(_kHighScore, v);

  int get totalCoins => _p.getInt(_kTotalCoins) ?? 0;
  Future<void> setTotalCoins(int v) => _p.setInt(_kTotalCoins, v);

  int get gamesPlayed => _p.getInt(_kGamesPlayed) ?? 0;
  Future<void> setGamesPlayed(int v) => _p.setInt(_kGamesPlayed, v);

  String get playerName => _p.getString(_kPlayerName) ?? 'Player';
  Future<void> setPlayerName(String v) => _p.setString(_kPlayerName, v);

  Difficulty get difficulty {
    final s = _p.getString(_kDifficulty);
    return Difficulty.values.firstWhere(
      (d) => d.name == s,
      orElse: () => Difficulty.normal,
    );
  }

  Future<void> setDifficulty(Difficulty d) => _p.setString(_kDifficulty, d.name);

  bool get muted => _p.getBool(_kMuted) ?? false;
  Future<void> setMuted(bool v) => _p.setBool(_kMuted, v);

  double get volume => _p.getDouble(_kVolume) ?? 0.8;
  Future<void> setVolume(double v) => _p.setDouble(_kVolume, v);

  String get selectedSkin => _p.getString(_kSelectedSkin) ?? 'classic';
  Future<void> setSelectedSkin(String v) => _p.setString(_kSelectedSkin, v);

  List<String> get unlockedSkins =>
      _p.getStringList(_kUnlockedSkins) ?? ['classic'];
  Future<void> setUnlockedSkins(List<String> v) =>
      _p.setStringList(_kUnlockedSkins, v);

  String get selectedPipeTheme => _p.getString(_kSelectedPipeTheme) ?? 'green';
  Future<void> setSelectedPipeTheme(String v) =>
      _p.setString(_kSelectedPipeTheme, v);

  List<String> get unlockedPipeThemes =>
      _p.getStringList(_kUnlockedPipeThemes) ?? ['green'];
  Future<void> setUnlockedPipeThemes(List<String> v) =>
      _p.setStringList(_kUnlockedPipeThemes, v);

  List<String> get unlockedAchievements =>
      _p.getStringList(_kAchievements) ?? [];
  Future<void> setUnlockedAchievements(List<String> v) =>
      _p.setStringList(_kAchievements, v);

  List<LeaderboardEntry> get leaderboard {
    final raw = _p.getString(_kLeaderboard);
    if (raw == null) return [];
    try {
      final list = jsonDecode(raw) as List<dynamic>;
      return list
          .map((e) => LeaderboardEntry.fromJson(e as Map<String, dynamic>))
          .toList();
    } catch (_) {
      return [];
    }
  }

  Future<void> setLeaderboard(List<LeaderboardEntry> entries) {
    final raw = jsonEncode(entries.map((e) => e.toJson()).toList());
    return _p.setString(_kLeaderboard, raw);
  }
}

// ============================================================

/// Sound effects are currently no-ops. This project originally played
/// flap/point/crash sounds via the `audioplayers` package, but a newer
/// release of that package pulled in Dart's native-assets/`objective_c`
/// bindings, which have an unresolved bug that crashes Windows builds
/// whenever any part of the file path contains a space (a very common
/// situation — see https://github.com/dart-lang/native/pull/3378).
///
/// Every call site elsewhere in this file (playFlap/playPoint/playCrash/
/// setVolume/setMuted/dispose) is unchanged — only this class's internals
/// were gutted — so nothing else needed to be edited. Haptic feedback
/// (HapticFeedback.*, called alongside these at every call site) still
/// provides tactile feedback in the meantime.
///
/// To restore real sound once that upstream bug is fixed: add
/// `audioplayers` back to pubspec.yaml (pin an EXACT version, not a `^`
/// range, and re-check after every `flutter pub get` that `objective_c`
/// hasn't reappeared), add real audio files under `assets/sounds/` and
/// declare them in pubspec.yaml, then reintroduce `AudioPlayer` instances
/// and real playback calls in the methods below.
class SoundManager {
  double _volume = 0.8;
  bool _muted = false;

  void setVolume(double v) {
    _volume = v.clamp(0.0, 1.0);
  }

  void setMuted(bool m) {
    _muted = m;
  }

  Future<void> playFlap() async {}
  Future<void> playPoint() async {}
  Future<void> playCrash() async {}

  void dispose() {}
}

// ============================================================

class GamePainter extends CustomPainter {
  final double birdY;
  final double birdX;
  final double birdRadius;
  final double birdRotation;
  final double flapAnim; // 0..1, 1 = just flapped (squash), decays to 0
  final List<Pipe> pipes;
  final double pipeWidth;
  final double floorY;
  final ui.Image? birdImage;
  final int? birdTint; // ARGB tint colour for the selected skin, or null
  final PipeTheme pipeTheme;
  final List<Coin> coins;
  final List<Particle> particles;
  final double parallaxOffset; // accumulated background scroll distance
  final bool hasShield;
  // When true, the flat sky/cloud background is skipped so a video widget
  // placed behind this CustomPaint is visible instead.
  final bool skipSky;

  GamePainter({
    required this.birdY,
    required this.birdX,
    required this.birdRadius,
    required this.birdRotation,
    required this.flapAnim,
    required this.pipes,
    required this.pipeWidth,
    required this.floorY,
    required this.pipeTheme,
    required this.coins,
    required this.particles,
    required this.parallaxOffset,
    required this.hasShield,
    this.birdImage,
    this.birdTint,
    this.skipSky = false,
  });

  @override
  void paint(Canvas canvas, Size size) {
    if (!skipSky) {
      _paintParallaxSky(canvas, size);
    }

    _paintPipes(canvas);
    _paintCoins(canvas);

    // Ground
    final groundPaint = Paint()..color = const Color(0xFFDED895);
    canvas.drawRect(
      Rect.fromLTWH(0, floorY, size.width, size.height - floorY),
      groundPaint,
    );
    final groundStripePaint = Paint()..color = const Color(0xFFC8B968);
    canvas.drawRect(Rect.fromLTWH(0, floorY, size.width, 8), groundStripePaint);

    _paintBird(canvas);
    _paintParticles(canvas);
  }

  void _paintParallaxSky(Canvas canvas, Size size) {
    final skyPaint = Paint()..color = const Color(0xFF70C5CE);
    canvas.drawRect(Rect.fromLTWH(0, 0, size.width, size.height), skyPaint);

    // Far layer: soft hills, scroll slowest.
    final hillPaint = Paint()..color = const Color(0xFF5FB3C4);
    final hillOffset = (parallaxOffset * 0.15) % size.width;
    for (final baseX in [-hillOffset, size.width - hillOffset]) {
      final path = Path()
        ..moveTo(baseX, size.height * 0.62)
        ..quadraticBezierTo(baseX + size.width * 0.25, size.height * 0.45,
            baseX + size.width * 0.5, size.height * 0.62)
        ..quadraticBezierTo(baseX + size.width * 0.75, size.height * 0.78,
            baseX + size.width, size.height * 0.62)
        ..lineTo(baseX + size.width, floorY)
        ..lineTo(baseX, floorY)
        ..close();
      canvas.drawPath(path, hillPaint);
    }

    // Near layer: clouds, scroll a bit faster.
    final cloudPaint = Paint()..color = Colors.white.withOpacity(0.6);
    final cloudOffset = (parallaxOffset * 0.35) % (size.width + 160);
    for (final baseX in [
      size.width * 0.2 - cloudOffset,
      size.width * 0.75 - cloudOffset,
      size.width * 1.3 - cloudOffset,
    ]) {
      canvas.drawCircle(Offset(baseX, size.height * 0.15), 20, cloudPaint);
      canvas.drawCircle(Offset(baseX + 20, size.height * 0.15 + 5), 16, cloudPaint);
    }
  }

  void _paintPipes(Canvas canvas) {
    final pipeBodyPaint = Paint()..color = Color(pipeTheme.bodyColor);
    final pipeEdgePaint = Paint()..color = Color(pipeTheme.edgeColor);
    // Reused for every pipe's image draws — Paint itself doesn't hold the
    // image (that's passed separately to drawImageRect each time), so one
    // instance works fine regardless of which picture a given pipe has.
    final imgPaint = Paint()..filterQuality = FilterQuality.medium;

    // Draws one solid pipe segment: tiles this specific pipe's picture
    // (each pipe may have a different one, or none) repeatedly down the
    // segment, otherwise fills with the pipe-theme's solid color. Tiling
    // (rather than stretching one image across the whole segment) keeps
    // the picture looking natural no matter how tall a segment ends up
    // being.
    void drawSegment(Rect rect, ui.Image? img) {
      if (img == null) {
        canvas.drawRect(rect, pipeBodyPaint);
        return;
      }
      final srcRect = Rect.fromLTWH(0, 0, img.width.toDouble(), img.height.toDouble());
      canvas.save();
      canvas.clipRect(rect);
      final tileHeight = pipeWidth * (img.height / img.width);
      double y = rect.top;
      while (y < rect.bottom) {
        canvas.drawImageRect(
          img,
          srcRect,
          Rect.fromLTWH(rect.left, y, pipeWidth, tileHeight),
          imgPaint,
        );
        y += tileHeight;
      }
      canvas.restore();
    }

    for (final pipe in pipes) {
      final zones = pipe.gapZones();
      double cursor = 0;
      for (final z in zones) {
        if (z.top > cursor) {
          drawSegment(Rect.fromLTWH(pipe.x, cursor, pipeWidth, z.top - cursor), pipe.pipeImage);
          // lip at the bottom of this solid segment (top of the gap)
          canvas.drawRect(
            Rect.fromLTWH(pipe.x - 4, z.top - 24, pipeWidth + 8, 24),
            pipeEdgePaint,
          );
        }
        cursor = z.bottom;
      }
      if (cursor < floorY) {
        drawSegment(Rect.fromLTWH(pipe.x, cursor, pipeWidth, floorY - cursor), pipe.pipeImage);
        canvas.drawRect(
          Rect.fromLTWH(pipe.x - 4, cursor, pipeWidth + 8, 24),
          pipeEdgePaint,
        );
      }

      if (pipe.hasPowerUp && !pipe.powerUpCollected) {
        _paintPowerUp(canvas, pipe.x + pipeWidth / 2, pipe.gapCenter, pipe.powerUpType!);
      }

    }
  }

  void _paintPowerUp(Canvas canvas, double x, double y, PowerUpType type) {
    final center = Offset(x, y);
    switch (type) {
      case PowerUpType.shield:
        final paint = Paint()..color = const Color(0xFF64B5F6);
        canvas.drawCircle(center, 14, paint);
        final ring = Paint()
          ..color = Colors.white
          ..style = PaintingStyle.stroke
          ..strokeWidth = 2.5;
        canvas.drawCircle(center, 14, ring);
        break;
      case PowerUpType.slowMo:
        final paint = Paint()..color = const Color(0xFFAB47BC);
        canvas.drawCircle(center, 14, paint);
        final hand = Paint()
          ..color = Colors.white
          ..strokeWidth = 2
          ..style = PaintingStyle.stroke;
        canvas.drawLine(center, center + const Offset(0, -8), hand);
        canvas.drawLine(center, center + const Offset(5, 3), hand);
        break;
      case PowerUpType.magnet:
        final paint = Paint()..color = const Color(0xFFE53935);
        canvas.drawCircle(center, 14, paint);
        final arc = Paint()
          ..color = Colors.white
          ..strokeWidth = 3
          ..style = PaintingStyle.stroke;
        canvas.drawArc(Rect.fromCenter(center: center, width: 16, height: 16),
            0.3, pi - 0.6, false, arc);
        break;
    }
  }

  void _paintCoins(Canvas canvas) {
    for (final c in coins) {
      if (c.collected) continue;
      final paint = Paint()..color = const Color(0xFFFFD54F);
      canvas.drawCircle(Offset(c.x, c.y), 10, paint);
      final ring = Paint()
        ..color = const Color(0xFFC98F0A)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 2;
      canvas.drawCircle(Offset(c.x, c.y), 10, ring);
      final tp = TextPainter(
        text: const TextSpan(
          text: '\u20b1',
          style: TextStyle(
              color: Color(0xFF8A6D00), fontSize: 12, fontWeight: FontWeight.bold),
        ),
        textDirection: TextDirection.ltr,
      )..layout();
      tp.paint(canvas, Offset(c.x - tp.width / 2, c.y - tp.height / 2));
    }
  }

  void _paintParticles(Canvas canvas) {
    for (final p in particles) {
      final t = (p.life / p.maxLife).clamp(0.0, 1.0);
      final paint = Paint()..color = Color(p.colorValue).withOpacity(t);
      canvas.drawCircle(Offset(p.x, p.y), 4 * t + 1, paint);
    }
  }

  void _paintBird(Canvas canvas) {
    canvas.save();
    canvas.translate(birdX, birdY);
    canvas.rotate(birdRotation);

    // Squash-and-stretch flap pulse: compress vertically, stretch
    // horizontally right after a flap, easing back to normal.
    final squash = 1.0 - 0.22 * flapAnim;
    final stretch = 1.0 + 0.14 * flapAnim;
    canvas.scale(stretch, squash);

    if (hasShield) {
      final shieldPaint = Paint()
        ..color = const Color(0xFF64B5F6).withOpacity(0.35)
        ..style = PaintingStyle.fill;
      canvas.drawCircle(Offset.zero, birdRadius * 1.5, shieldPaint);
      final shieldRing = Paint()
        ..color = const Color(0xFF2196F3)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 2.5;
      canvas.drawCircle(Offset.zero, birdRadius * 1.5, shieldRing);
    }

    if (birdImage != null) {
      final imgSize = birdRadius * 2.6;
      final destRect =
          Rect.fromCenter(center: Offset.zero, width: imgSize, height: imgSize);
      final srcRect = Rect.fromLTWH(
          0, 0, birdImage!.width.toDouble(), birdImage!.height.toDouble());
      final paint = Paint()..filterQuality = FilterQuality.medium;
      if (birdTint != null) {
        paint.colorFilter = ColorFilter.mode(Color(birdTint!), BlendMode.srcATop);
      }
      canvas.drawImageRect(birdImage!, srcRect, destRect, paint);
    } else {
      final bodyColor = birdTint != null ? Color(birdTint!) : const Color(0xFFF7D51D);
      final bodyPaint = Paint()..color = bodyColor;
      canvas.drawCircle(Offset.zero, birdRadius, bodyPaint);

      final wingPaint = Paint()..color = bodyColor.withOpacity(0.75);
      canvas.drawOval(
        Rect.fromCenter(
            center: const Offset(-2, 4), width: birdRadius * 1.1, height: birdRadius * 0.7),
        wingPaint,
      );

      final eyeWhitePaint = Paint()..color = Colors.white;
      canvas.drawCircle(Offset(birdRadius * 0.35, -birdRadius * 0.35), 5, eyeWhitePaint);
      final eyePupilPaint = Paint()..color = Colors.black;
      canvas.drawCircle(Offset(birdRadius * 0.45, -birdRadius * 0.35), 2.4, eyePupilPaint);

      final beakPaint = Paint()..color = const Color(0xFFEE8A1E);
      final beakPath = Path()
        ..moveTo(birdRadius * 0.8, 0)
        ..lineTo(birdRadius * 1.5, -3)
        ..lineTo(birdRadius * 1.5, 6)
        ..lineTo(birdRadius * 0.8, 4)
        ..close();
      canvas.drawPath(beakPath, beakPaint);
    }

    canvas.restore();
  }

  @override
  bool shouldRepaint(covariant GamePainter oldDelegate) => true;
}

// ============================================================

enum GameState { menu, leaderboard, playing, gameOver, won }

class GameScreen extends StatefulWidget {
  const GameScreen({super.key});

  @override
  State<GameScreen> createState() => _GameScreenState();
}

class _GameScreenState extends State<GameScreen>
    with SingleTickerProviderStateMixin {
  // Base pipe layout. Actual gap/speed are derived from difficulty + score
  // via _currentGapHeight() / _currentPipeSpeed().
  static const double birdRadius = 18;
  static const int winScore = 50;
  static const int leaderboardSize = 10;

  late Ticker _ticker;
  Duration _lastTick = Duration.zero;

  final PersistenceService _persistence = PersistenceService();
  final SoundManager _sound = SoundManager();
  bool _persistenceReady = false;

  double birdY = 0;
  double birdVelocity = 0;
  double birdRotation = 0;
  double _flapAnim = 0;

  List<Pipe> pipes = [];
  List<Coin> coins = [];
  List<Particle> particles = [];

  int score = 0;
  int highScore = 0;
  int sessionCoins = 0;
  int totalCoins = 0;
  int gamesPlayed = 0;
  double _parallaxOffset = 0;

  List<LeaderboardEntry> leaderboard = [];
  Set<String> unlockedAchievementIds = {};
  Set<String> unlockedSkinIds = {'classic'};
  Set<String> unlockedPipeThemeIds = {'green'};
  String selectedSkinId = 'classic';
  String selectedPipeThemeId = 'green';
  final List<Achievement> _achievements = buildAchievements();

  Difficulty difficulty = Difficulty.normal;
  GameState state = GameState.menu;

  bool paused = false;
  bool showSettings = false;
  bool _scoreSaved = false;
  final TextEditingController _nameController = TextEditingController();

  bool hasShield = false;
  double slowMoTimeLeft = 0;
  double magnetTimeLeft = 0;

  double _screenWidth = 400;
  double _screenHeight = 700;
  final Random _rand = Random();

  ui.Image? _birdImage;
  List<ui.Image> _pipeImages = [];
  VideoPlayerController? _bgController;
  bool _muted = false;
  double _volume = 0.8;

  double get birdX => _screenWidth * 0.22;
  double get pipeWidth => (_screenWidth * 0.17).clamp(56.0, 90.0);
  double get pipeSpacing => (_screenWidth * 0.62).clamp(230.0, 340.0);
  double get floorY => _screenHeight - (_screenHeight * 0.085).clamp(50.0, 70.0);

  DifficultySettings get _settings => DifficultySettings.forMode(difficulty);

  BirdSkin get _currentSkin =>
      kBirdSkins.firstWhere((s) => s.id == selectedSkinId, orElse: () => kBirdSkins.first);
  PipeTheme get _currentPipeTheme =>
      kPipeThemes.firstWhere((t) => t.id == selectedPipeThemeId, orElse: () => kPipeThemes.first);

  @override
  void initState() {
    super.initState();
    _ticker = createTicker(_onTick);
    _resetBird();
    _loadBirdImage();
    _loadPipeImages();
    _loadBackgroundVideo();
    _loadPersistence();
  }

  Future<void> _loadPersistence() async {
    await _persistence.init();
    highScore = _persistence.highScore;
    totalCoins = _persistence.totalCoins;
    gamesPlayed = _persistence.gamesPlayed;
    leaderboard = _persistence.leaderboard;
    unlockedAchievementIds = _persistence.unlockedAchievements.toSet();
    unlockedSkinIds = _persistence.unlockedSkins.toSet();
    unlockedPipeThemeIds = _persistence.unlockedPipeThemes.toSet();
    selectedSkinId = _persistence.selectedSkin;
    selectedPipeThemeId = _persistence.selectedPipeTheme;
    difficulty = _persistence.difficulty;
    _muted = _persistence.muted;
    _volume = _persistence.volume;
    _nameController.text = _persistence.playerName;
    _sound.setMuted(_muted);
    _sound.setVolume(_volume);
    if (mounted) {
      setState(() => _persistenceReady = true);
    }
  }

  Future<void> _loadBackgroundVideo() async {
    final controller = VideoPlayerController.asset('assets/videos/background.mp4');
    try {
      await controller.initialize();
      controller.setLooping(true);
      controller.setVolume(0);
      if (mounted) {
        setState(() => _bgController = controller);
      } else {
        controller.dispose();
      }
    } catch (_) {
      // Background video asset missing — the flat sky is used everywhere,
      // including on the game-over screen, so this is non-fatal.
    }
  }

  Future<void> _loadBirdImage() async {
    final data = await rootBundle.load('assets/images/bird.jpg');
    final codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
    final frame = await codec.getNextFrame();
    if (mounted) {
      setState(() => _birdImage = frame.image);
    }
  }

  // Loads as many numbered pipe pictures as exist — assets/images/pipe1.jpg,
  // pipe2.jpg, pipe3.jpg, and so on, up to _maxPipeImageSlots. You don't
  // need to provide all of them or keep them contiguous (e.g. having only
  // pipe1.jpg and pipe4.jpg is fine) — each missing number is just skipped
  // silently. Whichever ones load successfully get randomly assigned to
  // pipes as they spawn (see _spawnPipe), so pillars vary in appearance.
  static const int _maxPipeImageSlots = 8;

  Future<void> _loadPipeImages() async {
    final loaded = <ui.Image>[];
    for (int i = 1; i <= _maxPipeImageSlots; i++) {
      try {
        final data = await rootBundle.load('assets/images/pipe$i.jpg');
        final codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
        final frame = await codec.getNextFrame();
        loaded.add(frame.image);
      } catch (_) {
        // No file at this number — skip it and keep checking the rest.
      }
    }
    if (mounted) {
      setState(() => _pipeImages = loaded);
    }
  }

  void _resetBird() {
    birdY = 0;
    birdVelocity = 0;
    birdRotation = 0;
    _flapAnim = 0;
  }

  // ----------------------- TICK / UPDATE -----------------------

  void _onTick(Duration elapsed) {
    if (_lastTick == Duration.zero) {
      _lastTick = elapsed;
      return;
    }
    double dt = (elapsed - _lastTick).inMicroseconds / 1e6;
    _lastTick = elapsed;
    if (dt > 0.05) dt = 0.05;

    if (state == GameState.playing && !paused) {
      setState(() => _update(dt));
    } else if (particles.isNotEmpty) {
      // Let a crash's particle burst keep animating even after the run ends.
      setState(() => _updateParticles(dt));
    }
  }

  void _updateParticles(double dt) {
    for (final p in particles) {
      p.x += p.vx * dt;
      p.y += p.vy * dt;
      p.vy += 600 * dt;
      p.life -= dt;
    }
    particles.removeWhere((p) => p.life <= 0);
  }

  double _currentGapHeight() {
    final base = _settings.gapHeight;
    final shrink = (score ~/ 5) * 4.0;
    return (base - shrink).clamp(110.0, base);
  }

  double _currentPipeSpeed() {
    final base = _settings.pipeSpeed;
    final boost = (score ~/ 5) * 6.0;
    return (base + boost).clamp(base, base + 120.0);
  }

  void _update(double dt) {
    final slowMo = slowMoTimeLeft > 0;
    final effectiveDt = slowMo ? dt * 0.5 : dt;

    if (slowMoTimeLeft > 0) slowMoTimeLeft = max(0, slowMoTimeLeft - dt);
    if (magnetTimeLeft > 0) magnetTimeLeft = max(0, magnetTimeLeft - dt);
    if (_flapAnim > 0) _flapAnim = max(0, _flapAnim - dt / 0.18);

    birdVelocity += _settings.gravity * effectiveDt;
    birdY += birdVelocity * effectiveDt;
    birdRotation = (birdVelocity / 700).clamp(-0.6, 1.2);

    final pipeSpeed = _currentPipeSpeed();
    _parallaxOffset += pipeSpeed * effectiveDt;

    for (final pipe in pipes) {
      pipe.x -= pipeSpeed * effectiveDt;
      if (pipe.moving) {
        pipe.driftPhase += pipe.driftSpeed * dt;
        final margin = 70.0;
        pipe.gapCenter = (pipe.baseGapCenter + sin(pipe.driftPhase) * pipe.driftRange)
            .clamp(margin + pipe.gapHeight / 2, floorY - margin - pipe.gapHeight / 2);
      }
    }
    pipes.removeWhere((p) => p.x < -pipeWidth);

    for (final c in coins) {
      c.x -= pipeSpeed * effectiveDt;
      if (magnetTimeLeft > 0 && !c.collected) {
        final d = distanceBetween(birdX, birdY, c.x, c.y);
        if (d < 170 && d > 1) {
          c.x += (birdX - c.x) * min(1.0, 4 * dt);
          c.y += (birdY - c.y) * min(1.0, 4 * dt);
        }
      }
    }
    coins.removeWhere((c) => c.x < -30 || c.collected);

    if (pipes.isEmpty || pipes.last.x < _screenWidth - pipeSpacing) {
      _spawnPipe();
    }

    for (final pipe in pipes) {
      if (!pipe.scored && pipe.x + pipeWidth < birdX) {
        pipe.scored = true;
        score++;
        _sound.playPoint();
      }
    }

    if (score >= winScore) {
      _winGame();
      return;
    }

    for (final pipe in pipes) {
      if (pipe.hasPowerUp && !pipe.powerUpCollected) {
        final d = distanceBetween(birdX, birdY, pipe.x + pipeWidth / 2, pipe.gapCenter);
        if (d < birdRadius + 16) {
          pipe.powerUpCollected = true;
          _activatePowerUp(pipe.powerUpType!);
        }
      }
    }
    for (final c in coins) {
      if (!c.collected && distanceBetween(birdX, birdY, c.x, c.y) < birdRadius + 12) {
        c.collected = true;
        sessionCoins++;
      }
    }

    if (birdY - birdRadius <= 0) {
      birdY = birdRadius;
      birdVelocity = 0;
    }
    if (birdY + birdRadius >= floorY) {
      birdY = floorY - birdRadius;
      _handleHit();
      return;
    }

    for (final pipe in pipes) {
      for (final rect in _solidRectsForPipe(pipe)) {
        if (circleIntersectsRect(
            birdX, birdY, birdRadius, rect.left, rect.top, rect.right, rect.bottom)) {
          _handleHit();
          return;
        }
      }
    }
  }

  List<Rect> _solidRectsForPipe(Pipe pipe) {
    final zones = pipe.gapZones();
    final rects = <Rect>[];
    double cursor = 0;
    for (final z in zones) {
      if (z.top > cursor) {
        rects.add(Rect.fromLTWH(pipe.x, cursor, pipeWidth, z.top - cursor));
      }
      cursor = z.bottom;
    }
    if (cursor < floorY) {
      rects.add(Rect.fromLTWH(pipe.x, cursor, pipeWidth, floorY - cursor));
    }
    return rects;
  }

  void _spawnPipe() {
    final gapHeight = _currentGapHeight();
    final margin = 70.0;
    final available = (floorY - margin * 2 - gapHeight).clamp(40.0, double.infinity);
    final gapCenter = margin + gapHeight / 2 + _rand.nextDouble() * available;

    final movingChance = score >= 15 ? 0.35 : 0.0;
    final doubleChance = score >= 30 ? 0.2 : 0.0;
    final isDouble = _rand.nextDouble() < doubleChance;
    final isMoving = !isDouble && _rand.nextDouble() < movingChance;

    double? secondGapCenter;
    double? secondGapHeight;
    if (isDouble) {
      secondGapHeight = gapHeight * 0.8;
      const barHeight = 60.0;
      final minCenter = margin + secondGapHeight / 2;
      final maxCenter = floorY - margin - secondGapHeight / 2;
      secondGapCenter =
          (gapCenter + gapHeight / 2 + barHeight + secondGapHeight / 2).clamp(minCenter, maxCenter);
    }

    final hasPowerUp = !isDouble && _rand.nextDouble() < 0.12;
    PowerUpType? powerUpType;
    if (hasPowerUp) {
      powerUpType = PowerUpType.values[_rand.nextInt(PowerUpType.values.length)];
    }

    // Randomly pick one of the loaded pipe pictures for this specific
    // pipe, so pillars vary in appearance as you play. Falls back to null
    // (solid theme color) if no pipe pictures have been provided.
    final pipeImage =
        _pipeImages.isEmpty ? null : _pipeImages[_rand.nextInt(_pipeImages.length)];

    pipes.add(Pipe(
      x: _screenWidth,
      gapCenter: gapCenter,
      gapHeight: gapHeight,
      moving: isMoving,
      driftRange: isMoving ? 40 + _rand.nextDouble() * 30 : 0,
      driftSpeed: isMoving ? 1.2 + _rand.nextDouble() * 0.8 : 0,
      isDouble: isDouble,
      secondGapCenter: secondGapCenter,
      secondGapHeight: secondGapHeight,
      hasPowerUp: hasPowerUp,
      powerUpType: powerUpType,
      pipeImage: pipeImage,
    ));

    if (!hasPowerUp && _rand.nextDouble() < 0.5) {
      coins.add(Coin(x: _screenWidth + pipeWidth / 2, y: gapCenter));
    }
  }

  void _activatePowerUp(PowerUpType type) {
    HapticFeedback.selectionClick();
    switch (type) {
      case PowerUpType.shield:
        hasShield = true;
        break;
      case PowerUpType.slowMo:
        slowMoTimeLeft = 6.0;
        break;
      case PowerUpType.magnet:
        magnetTimeLeft = 7.0;
        break;
    }
  }

  void _spawnParticles(double x, double y, Color color) {
    for (int i = 0; i < 18; i++) {
      final angle = _rand.nextDouble() * 2 * pi;
      final speed = 60 + _rand.nextDouble() * 180;
      particles.add(Particle(
        x: x,
        y: y,
        vx: cos(angle) * speed,
        vy: sin(angle) * speed - 80,
        life: 0.5 + _rand.nextDouble() * 0.4,
        colorValue: color.value,
      ));
    }
  }

  void _handleHit() {
    if (hasShield) {
      hasShield = false;
      _spawnParticles(birdX, birdY, const Color(0xFF64B5F6));
      HapticFeedback.mediumImpact();
      // A shield absorbs the hit but the bird keeps flying — bounce it up
      // slightly so it doesn't immediately clip the same pipe again.
      birdVelocity = min(birdVelocity, -200);
      return;
    }
    _spawnParticles(birdX, birdY, const Color(0xFFF7D51D));
    _endGame();
  }

  // ----------------------- GAME LIFECYCLE -----------------------

  Future<void> _persistRunResults() async {
    if (score > highScore) {
      highScore = score;
      await _persistence.setHighScore(highScore);
    }
    gamesPlayed++;
    await _persistence.setGamesPlayed(gamesPlayed);
    totalCoins += sessionCoins;
    await _persistence.setTotalCoins(totalCoins);
    _checkAchievements();
  }

  void _checkAchievements() {
    final stats =
        GameStats(bestScore: highScore, gamesPlayed: gamesPlayed, totalCoins: totalCoins);
    final newlyUnlocked = <Achievement>[];
    for (final a in _achievements) {
      if (!unlockedAchievementIds.contains(a.id) && a.isUnlocked(stats)) {
        unlockedAchievementIds.add(a.id);
        newlyUnlocked.add(a);
      }
    }
    if (newlyUnlocked.isNotEmpty) {
      _persistence.setUnlockedAchievements(unlockedAchievementIds.toList());
      for (final a in newlyUnlocked) {
        _showAchievementToast(a);
      }
    }
  }

  void _showAchievementToast(Achievement a) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('🏆 Achievement unlocked: ${a.title}'),
        duration: const Duration(seconds: 3),
        backgroundColor: const Color(0xFF8A6D00),
      ),
    );
  }

  bool _qualifiesForLeaderboard(int s) {
    if (s <= 0) return false;
    if (leaderboard.length < leaderboardSize) return true;
    final sorted = [...leaderboard]..sort((a, b) => b.score.compareTo(a.score));
    return s > sorted.last.score;
  }

  Future<void> _saveToLeaderboard() async {
    final name = _nameController.text.trim().isEmpty ? 'Player' : _nameController.text.trim();
    await _persistence.setPlayerName(name);
    leaderboard.add(LeaderboardEntry(name, score));
    leaderboard.sort((a, b) => b.score.compareTo(a.score));
    if (leaderboard.length > leaderboardSize) {
      leaderboard = leaderboard.sublist(0, leaderboardSize);
    }
    await _persistence.setLeaderboard(leaderboard);
    setState(() => _scoreSaved = true);
  }

  void _playEndVideo() {
    final controller = _bgController;
    if (controller == null) return;
    controller.seekTo(Duration.zero);
    controller.setVolume(_muted ? 0.0 : 1.0);
    controller.play();
  }

  void _pauseEndVideo() {
    _bgController?.pause();
  }

  void _endGame() {
    if (state != GameState.playing) return;
    state = GameState.gameOver;
    _ticker.stop();
    _playEndVideo();
    HapticFeedback.heavyImpact();
    _sound.playCrash();
    _persistRunResults();
    setState(() {});
  }

  void _winGame() {
    if (state != GameState.playing) return;
    state = GameState.won;
    _ticker.stop();
    _pauseEndVideo();
    HapticFeedback.mediumImpact();
    _persistRunResults();
    setState(() {});
  }

  void _startGame() {
    _pauseEndVideo();
    _resetBird();
    setState(() {
      state = GameState.playing;
      pipes.clear();
      coins.clear();
      particles.clear();
      score = 0;
      sessionCoins = 0;
      hasShield = false;
      slowMoTimeLeft = 0;
      magnetTimeLeft = 0;
      paused = false;
      _scoreSaved = false;
      birdY = _screenHeight / 2;
      birdVelocity = _settings.flapVelocity * 0.6;
      _lastTick = Duration.zero;
    });
    _ticker.start();
  }

  void _goToMenu() {
    _pauseEndVideo();
    setState(() {
      state = GameState.menu;
      showSettings = false;
      paused = false;
    });
  }

  void _openLeaderboard() {
    setState(() => state = GameState.leaderboard);
  }

  void _togglePause() {
    if (state != GameState.playing) return;
    setState(() => paused = !paused);
  }

  void _toggleMute() {
    setState(() => _muted = !_muted);
    _bgController?.setVolume(_muted ? 0.0 : 1.0);
    _sound.setMuted(_muted);
    _persistence.setMuted(_muted);
  }

  void _setVolume(double v) {
    setState(() => _volume = v);
    _sound.setVolume(v);
    _persistence.setVolume(v);
  }

  void _setDifficulty(Difficulty d) {
    setState(() => difficulty = d);
    _persistence.setDifficulty(d);
  }

  void _selectSkin(BirdSkin skin) {
    if (unlockedSkinIds.contains(skin.id)) {
      setState(() => selectedSkinId = skin.id);
      _persistence.setSelectedSkin(skin.id);
    } else if (totalCoins >= skin.unlockCoinCost) {
      setState(() {
        totalCoins -= skin.unlockCoinCost;
        unlockedSkinIds.add(skin.id);
        selectedSkinId = skin.id;
      });
      _persistence.setTotalCoins(totalCoins);
      _persistence.setUnlockedSkins(unlockedSkinIds.toList());
      _persistence.setSelectedSkin(skin.id);
    }
  }

  void _selectPipeTheme(PipeTheme theme) {
    if (unlockedPipeThemeIds.contains(theme.id)) {
      setState(() => selectedPipeThemeId = theme.id);
      _persistence.setSelectedPipeTheme(theme.id);
    } else if (totalCoins >= theme.unlockCoinCost) {
      setState(() {
        totalCoins -= theme.unlockCoinCost;
        unlockedPipeThemeIds.add(theme.id);
        selectedPipeThemeId = theme.id;
      });
      _persistence.setTotalCoins(totalCoins);
      _persistence.setUnlockedPipeThemes(unlockedPipeThemeIds.toList());
      _persistence.setSelectedPipeTheme(theme.id);
    }
  }

  Future<void> _shareScore() async {
    // Using the clipboard instead of a share_plus share sheet — no extra
    // native dependency required, so it works the same on every platform.
    final text = 'I scored $score in Flappy Bird! Can you beat me?';
    await Clipboard.setData(ClipboardData(text: text));
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Score copied to clipboard!'), duration: Duration(seconds: 2)),
    );
  }

  void _flap() {
    if (state != GameState.playing || paused) return;
    setState(() {
      birdVelocity = _settings.flapVelocity;
      _flapAnim = 1.0;
    });
    HapticFeedback.lightImpact();
    _sound.playFlap();
  }

  @override
  void dispose() {
    _ticker.dispose();
    _bgController?.dispose();
    _sound.dispose();
    _nameController.dispose();
    super.dispose();
  }

  // ----------------------- BUILD -----------------------

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF70C5CE),
      body: LayoutBuilder(
        builder: (context, constraints) {
          _screenWidth = constraints.maxWidth;
          _screenHeight = constraints.maxHeight;
          if (state == GameState.menu && birdY == 0) {
            birdY = _screenHeight / 2;
          }

          final showVideo = state == GameState.gameOver &&
              _bgController != null &&
              _bgController!.value.isInitialized;

          return GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTapDown: (_) => _flap(),
            child: Stack(
              children: [
                if (showVideo)
                  Positioned.fill(
                    child: FittedBox(
                      fit: BoxFit.cover,
                      child: SizedBox(
                        width: _bgController!.value.size.width,
                        height: _bgController!.value.size.height,
                        child: VideoPlayer(_bgController!),
                      ),
                    ),
                  ),
                CustomPaint(
                  size: Size(_screenWidth, _screenHeight),
                  painter: GamePainter(
                    birdY: birdY,
                    birdX: birdX,
                    birdRadius: birdRadius,
                    birdRotation: birdRotation,
                    flapAnim: _flapAnim,
                    pipes: pipes,
                    pipeWidth: pipeWidth,
                    floorY: floorY,
                    birdImage: _birdImage,
                    birdTint: _currentSkin.colorValue,
                    pipeTheme: _currentPipeTheme,
                    coins: coins,
                    particles: particles,
                    parallaxOffset: _parallaxOffset,
                    hasShield: hasShield,
                    skipSky: showVideo,
                  ),
                ),
                if (state == GameState.playing) _buildHud(),
                if (state == GameState.menu && !showSettings) _buildMenuOverlay(),
                if (state == GameState.menu && showSettings) _buildSettingsOverlay(),
                if (state == GameState.leaderboard) _buildLeaderboardOverlay(),
                if (state == GameState.gameOver) _buildResultOverlay(isWin: false),
                if (state == GameState.won) _buildResultOverlay(isWin: true),
                if (state == GameState.playing && paused) _buildPauseOverlay(),
                if (state == GameState.playing)
                  Positioned(
                    top: 40,
                    right: 16,
                    child: _iconButton(
                      icon: paused ? Icons.play_arrow : Icons.pause,
                      onTap: _togglePause,
                    ),
                  ),
                if (state == GameState.gameOver)
                  Positioned(
                    top: 40,
                    right: 16,
                    child: _iconButton(
                      icon: _muted ? Icons.volume_off : Icons.volume_up,
                      onTap: _toggleMute,
                    ),
                  ),
              ],
            ),
          );
        },
      ),
    );
  }

  Widget _iconButton({required IconData icon, required VoidCallback onTap}) {
    return GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTapDown: (_) {},
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.all(8),
        decoration:
            BoxDecoration(color: Colors.black.withOpacity(0.35), shape: BoxShape.circle),
        child: Icon(icon, color: Colors.white, size: 22),
      ),
    );
  }

  Widget _buildHud() {
    return Positioned(
      top: 60,
      left: 0,
      right: 0,
      child: Column(
        children: [
          Text(
            '$score',
            textAlign: TextAlign.center,
            style: const TextStyle(
              fontSize: 56,
              fontWeight: FontWeight.bold,
              color: Colors.white,
              shadows: [Shadow(offset: Offset(2, 2), blurRadius: 2, color: Colors.black54)],
            ),
          ),
          const SizedBox(height: 4),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              if (sessionCoins > 0) _hudChip('\u20b1$sessionCoins', const Color(0xFFFFD54F)),
              if (hasShield) _hudChip('Shield', const Color(0xFF64B5F6)),
              if (slowMoTimeLeft > 0) _hudChip('Slow-Mo', const Color(0xFFAB47BC)),
              if (magnetTimeLeft > 0) _hudChip('Magnet', const Color(0xFFE53935)),
            ],
          ),
        ],
      ),
    );
  }

  Widget _hudChip(String label, Color color) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 3),
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
      decoration: BoxDecoration(color: color, borderRadius: BorderRadius.circular(12)),
      child: Text(label,
          style: const TextStyle(color: Colors.white, fontSize: 12, fontWeight: FontWeight.bold)),
    );
  }

  Widget _panel({required Widget child, double width = 280}) {
    return Positioned.fill(
      child: Container(
        color: Colors.black.withOpacity(0.35),
        alignment: Alignment.center,
        child: Container(
          width: width,
          constraints: BoxConstraints(maxHeight: _screenHeight * 0.85),
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 22),
          decoration: BoxDecoration(
            color: const Color(0xFFDED895),
            borderRadius: BorderRadius.circular(16),
            border: Border.all(color: Colors.brown, width: 3),
          ),
          child: SingleChildScrollView(child: child),
        ),
      ),
    );
  }

  ButtonStyle _btnStyle(Color bg, {EdgeInsets? padding}) => ElevatedButton.styleFrom(
        backgroundColor: bg,
        padding: padding ?? const EdgeInsets.symmetric(horizontal: 22, vertical: 12),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      );

  Widget _buildMenuOverlay() {
    return Positioned.fill(
      child: Container(
        alignment: Alignment.center,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'Flappy Bird',
              style: TextStyle(
                fontSize: 40,
                fontWeight: FontWeight.bold,
                color: Colors.white,
                shadows: [Shadow(offset: Offset(2, 2), blurRadius: 3, color: Colors.black54)],
              ),
            ),
            const SizedBox(height: 8),
            Text('Best: $highScore   \u20b1$totalCoins   (${DifficultySettings.label(difficulty)})',
                style: const TextStyle(color: Colors.white, fontSize: 15)),
            const SizedBox(height: 32),
            ElevatedButton(
              onPressed: _startGame,
              style: _btnStyle(Colors.orange,
                  padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 14)),
              child: const Text('Play', style: TextStyle(fontSize: 20, color: Colors.white)),
            ),
            const SizedBox(height: 14),
            ElevatedButton(
              onPressed: _openLeaderboard,
              style: _btnStyle(Colors.white),
              child: const Text('Leaderboard',
                  style: TextStyle(fontSize: 16, color: Colors.brown, fontWeight: FontWeight.w600)),
            ),
            const SizedBox(height: 14),
            ElevatedButton(
              onPressed: () => setState(() => showSettings = true),
              style: _btnStyle(Colors.white),
              child: const Text('Settings',
                  style: TextStyle(fontSize: 16, color: Colors.brown, fontWeight: FontWeight.w600)),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSettingsOverlay() {
    return _panel(
      width: 300,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Center(
            child: Text('Settings',
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Colors.brown)),
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              Icon(_muted ? Icons.volume_off : Icons.volume_up, color: Colors.brown),
              Expanded(
                child: Slider(
                  value: _volume,
                  onChanged: _muted ? null : _setVolume,
                  activeColor: Colors.orange,
                ),
              ),
              GestureDetector(onTap: _toggleMute, child: Icon(_muted ? Icons.check_box : Icons.check_box_outline_blank, color: Colors.brown)),
            ],
          ),
          const Text('Difficulty', style: TextStyle(fontWeight: FontWeight.bold, color: Colors.brown)),
          const SizedBox(height: 6),
          Wrap(
            spacing: 8,
            children: Difficulty.values.map((d) {
              final selected = d == difficulty;
              return ChoiceChip(
                label: Text(DifficultySettings.label(d)),
                selected: selected,
                selectedColor: Colors.orange,
                onSelected: (_) => _setDifficulty(d),
              );
            }).toList(),
          ),
          const SizedBox(height: 16),
          Text('Bird Skins (\u20b1$totalCoins available)',
              style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.brown)),
          const SizedBox(height: 6),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: kBirdSkins.map((skin) => _cosmeticChip(
                  label: skin.name,
                  selected: skin.id == selectedSkinId,
                  unlocked: unlockedSkinIds.contains(skin.id),
                  cost: skin.unlockCoinCost,
                  onTap: () => _selectSkin(skin),
                )).toList(),
          ),
          const SizedBox(height: 16),
          Text('Pipe Themes (\u20b1$totalCoins available)',
              style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.brown)),
          const SizedBox(height: 6),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: kPipeThemes.map((theme) => _cosmeticChip(
                  label: theme.name,
                  selected: theme.id == selectedPipeThemeId,
                  unlocked: unlockedPipeThemeIds.contains(theme.id),
                  cost: theme.unlockCoinCost,
                  onTap: () => _selectPipeTheme(theme),
                )).toList(),
          ),
          const SizedBox(height: 16),
          Text('Achievements (${unlockedAchievementIds.length}/${_achievements.length})',
              style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.brown)),
          const SizedBox(height: 6),
          ..._achievements.map((a) {
            final unlocked = unlockedAchievementIds.contains(a.id);
            return Padding(
              padding: const EdgeInsets.symmetric(vertical: 2),
              child: Row(
                children: [
                  Icon(unlocked ? Icons.emoji_events : Icons.lock_outline,
                      size: 16, color: unlocked ? const Color(0xFF8A6D00) : Colors.black38),
                  const SizedBox(width: 6),
                  Expanded(
                    child: Text(
                      '${a.title} — ${a.description}',
                      style: TextStyle(
                          fontSize: 12, color: unlocked ? Colors.black87 : Colors.black38),
                    ),
                  ),
                ],
              ),
            );
          }),
          const SizedBox(height: 20),
          Center(
            child: ElevatedButton(
              onPressed: () => setState(() => showSettings = false),
              style: _btnStyle(Colors.orange),
              child: const Text('Back', style: TextStyle(fontSize: 16, color: Colors.white)),
            ),
          ),
        ],
      ),
    );
  }

  Widget _cosmeticChip({
    required String label,
    required bool selected,
    required bool unlocked,
    required int cost,
    required VoidCallback onTap,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
        decoration: BoxDecoration(
          color: selected ? Colors.orange : Colors.white,
          borderRadius: BorderRadius.circular(8),
          border: Border.all(color: Colors.brown.withOpacity(0.4)),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            if (!unlocked) const Icon(Icons.lock, size: 12, color: Colors.black45),
            if (!unlocked) const SizedBox(width: 4),
            Text(
              unlocked ? label : '$label (\u20b1$cost)',
              style: TextStyle(
                fontSize: 12,
                color: selected ? Colors.white : Colors.black87,
                fontWeight: selected ? FontWeight.bold : FontWeight.normal,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLeaderboardOverlay() {
    return _panel(
      width: 260,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const Text('Leaderboard',
              style: TextStyle(fontSize: 26, fontWeight: FontWeight.bold, color: Colors.brown)),
          const SizedBox(height: 16),
          if (leaderboard.isEmpty)
            const Text('No scores yet — play a round!',
                textAlign: TextAlign.center, style: TextStyle(fontSize: 15, color: Colors.black54))
          else
            Column(
              children: List.generate(leaderboard.length, (i) {
                final entry = leaderboard[i];
                return Padding(
                  padding: const EdgeInsets.symmetric(vertical: 4),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text('#${i + 1}',
                          style: const TextStyle(
                              fontSize: 16, fontWeight: FontWeight.bold, color: Colors.brown)),
                      Expanded(
                        child: Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 8),
                          child: Text(entry.name,
                              overflow: TextOverflow.ellipsis,
                              style: const TextStyle(fontSize: 15, color: Colors.black87)),
                        ),
                      ),
                      Text('${entry.score}', style: const TextStyle(fontSize: 16, color: Colors.black87)),
                    ],
                  ),
                );
              }),
            ),
          const SizedBox(height: 20),
          ElevatedButton(
            onPressed: _goToMenu,
            style: _btnStyle(Colors.orange),
            child: const Text('Back', style: TextStyle(fontSize: 16, color: Colors.white)),
          ),
        ],
      ),
    );
  }

  Widget _buildPauseOverlay() {
    return Positioned.fill(
      child: Container(
        color: Colors.black.withOpacity(0.45),
        alignment: Alignment.center,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('Paused',
                style: TextStyle(fontSize: 32, fontWeight: FontWeight.bold, color: Colors.white)),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: _togglePause,
              style: _btnStyle(Colors.orange),
              child: const Text('Resume', style: TextStyle(fontSize: 16, color: Colors.white)),
            ),
            const SizedBox(height: 12),
            ElevatedButton(
              onPressed: _goToMenu,
              style: _btnStyle(Colors.white),
              child: const Text('Quit to Menu',
                  style: TextStyle(fontSize: 16, color: Colors.brown, fontWeight: FontWeight.w600)),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildResultOverlay({required bool isWin}) {
    final qualifies = _qualifiesForLeaderboard(score) && !_scoreSaved;
    return _panel(
      width: 300,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          if (isWin) ...[
            const Text('🎉 Congratulations! 🎉',
                textAlign: TextAlign.center,
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Color(0xFF8A6D00))),
            const SizedBox(height: 10),
            Text('You reached $winScore points!', style: const TextStyle(fontSize: 16, color: Colors.black87)),
            const SizedBox(height: 6),
            const Text('You have won ₱10!',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: Color(0xFF8A6D00))),
          ] else ...[
            const Text('Game Over',
                style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold, color: Colors.brown)),
            const SizedBox(height: 10),
            Text('Score: $score', style: const TextStyle(fontSize: 20, color: Colors.black87)),
            const SizedBox(height: 4),
            Text('Best: $highScore', style: const TextStyle(fontSize: 16, color: Colors.black54)),
          ],
          if (sessionCoins > 0) ...[
            const SizedBox(height: 6),
            Text('Coins earned: \u20b1$sessionCoins',
                style: const TextStyle(fontSize: 15, color: Color(0xFF8A6D00), fontWeight: FontWeight.w600)),
          ],
          if (qualifies) ...[
            const SizedBox(height: 16),
            const Text('New high score! Save it:', style: TextStyle(fontSize: 13, color: Colors.black54)),
            const SizedBox(height: 6),
            TextField(
              controller: _nameController,
              maxLength: 12,
              textAlign: TextAlign.center,
              decoration: const InputDecoration(
                counterText: '',
                border: OutlineInputBorder(),
                hintText: 'Your name / initials',
                contentPadding: EdgeInsets.symmetric(horizontal: 10, vertical: 8),
              ),
            ),
            const SizedBox(height: 8),
            ElevatedButton(
              onPressed: _saveToLeaderboard,
              style: _btnStyle(Colors.orange),
              child: const Text('Save Score', style: TextStyle(fontSize: 15, color: Colors.white)),
            ),
          ] else if (_scoreSaved) ...[
            const SizedBox(height: 12),
            const Text('Saved to leaderboard!', style: TextStyle(color: Color(0xFF2E7D32), fontSize: 13)),
          ],
          const SizedBox(height: 18),
          Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              ElevatedButton(
                onPressed: _startGame,
                style: _btnStyle(Colors.orange),
                child: const Text('Play Again', style: TextStyle(fontSize: 15, color: Colors.white)),
              ),
              const SizedBox(width: 10),
              ElevatedButton(
                onPressed: _goToMenu,
                style: _btnStyle(Colors.white),
                child: const Text('Menu',
                    style: TextStyle(fontSize: 15, color: Colors.brown, fontWeight: FontWeight.w600)),
              ),
              const SizedBox(width: 10),
              _iconButton(icon: Icons.share, onTap: _shareScore),
            ],
          ),
        ],
      ),
    );
  }
}

// ============================================================

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  // Allow landscape as well as portrait now — the game screen lays itself
  // out from the available width/height rather than assuming portrait.
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.landscapeLeft,
    DeviceOrientation.landscapeRight,
  ]);
  runApp(const FlappyBirdApp());
}

class FlappyBirdApp extends StatelessWidget {
  const FlappyBirdApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flappy Bird',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true, fontFamily: 'Arial'),
      home: const GameScreen(),
    );
  }
}